name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Action 7z
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./
          pathTarget: build.7z
