name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Action 7z
        uses: edgarrc/action-7z@v1.0.4
        with:
          args: 7z a -t7z -mx9 build.7z ./
      - name: upload 7z
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: build.7z
        
