name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: remove .git
        run: |
          rm -rf ./.git
          find . -name '*.bmp' -delete
          find . -name '*.png' -delete
          find . -name '*.zip' -delete
          mkdir artifact
          7z a -t7z -mx9 artifact/build.7z ./
      - name: upload 7z
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: artifact
      - name: Upload release asset
        if: github.event.action == 'published'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        

        
